version: "3.5"
services:
  go:
    image: golang:1.20
    container_name: go
    restart: always
    env_file:
      - .env
    volumes:
      - ./go/src:/go/src/github.com/tonywangcn/distributed-web-crawler
    working_dir: /go/src/github.com/tonywangcn/distributed-web-crawler
    command: [ "tail", "-f", "/dev/null" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  node:
    image: apify/actor-node-puppeteer-chrome:latest
    container_name: node
    env_file:
      - .env
    volumes:
      - "./node/:/code/"
    working_dir: /code/
    restart: always
    command: [ "tail", "-f", "/dev/null" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
